#!/usr/bin/env sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS.
DEFAULT_JVM_OPTS=""

# Use the POSIX C shell to find the java executable.
if [ -z "$JAVA_HOME" ]; then
  javaExecutable="$(command -v java)"
fi

if [ -z "$javaExecutable" ]; then
  echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
  echo "Please set JAVA_HOME or ensure java is installed."
  exit 1
fi

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the correct Java executable to use.
if [ -n "$JAVA_HOME" ]; then
  if [ -x "$JAVA_HOME/bin/java" ]; then
    JAVA_CMD="$JAVA_HOME/bin/java"
  else
    echo "ERROR: JAVA_HOME is set but does not point to a valid Java installation."
    exit 1
  fi
else
  JAVA_CMD="$javaExecutable"
fi

exec "$JAVA_CMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
